// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.vef.v0_1.types;

/**
 * WIT-generated record.
 *
 * @param s s
 * @param c c
 * @param p p
 */
public record Hold(Shape s, Color c, Perms p) {
}
