// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.mang.v0_1.mangled;

/** Nothing to see here. */
public interface Mangled {

    /** class_. */
    void class_();

    /**
     * wait_.
     *
     * @return wait_
     */
    int wait_();
}
