// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.mang.v0_1.mangled;

/**
 * WIT-generated record.
 *
 * @param toString_ toString_
 * @param hashCode_ hashCode_
 * @param equals_ equals_
 */
public record Pair(String toString_, long hashCode_, boolean equals_) {
}
