// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.bytes.v0_1.types;

import io.github.witjava.support.Result;

/** Nothing to see here. */
public interface Types {

    /**
     * Read every chunk.
     *
     * @return readAll
     */
    java.util.List<byte[]> readAll();

    /**
     * Data if any.
     *
     * @return maybeData
     */
    java.util.Optional<byte[]> maybeData();

    /**
     * First non-empty chunk.
     *
     * @param chunks chunks
     * @return firstOf
     */
    Result<byte[], String> firstOf(java.util.List<byte[]> chunks);
}
