//! Deterministic Java source renderer (spec §12). No templates, no locale,
//! explicit ordering everywhere, `\n` endings, no timestamps.

use crate::ir::{Decl, JavaFile, JavaProject, Method, Param, TypeRef};
use crate::naming::Fqn;
use crate::passes;
use std::collections::BTreeMap;

/// Renders the project to (relative path, content) pairs, sorted by path.
/// Errs on a duplicate output path — the FQN registry should make this
/// impossible; this is the backstop that keeps it from ever being a silent
/// overwrite.
pub fn render(
    project: &JavaProject,
    tool_version: &str,
    support_package: &str,
) -> Result<BTreeMap<String, String>, String> {
    let mut out = BTreeMap::new();
    let mut files: Vec<&JavaFile> = project.files.iter().collect();
    files.sort_by(|a, b| {
        a.package
            .cmp(&b.package)
            .then_with(|| a.file_name.cmp(&b.file_name))
    });
    for file in files {
        let header = format!("// @generated by wit-java {tool_version}, mapping v1 — DO NOT EDIT");
        let body = render_file(file, &header, support_package);
        let path = format!("{}/{}.java", file.package.replace('.', "/"), file.file_name);
        if out.insert(path.clone(), body).is_some() {
            return Err(format!("internal: duplicate output file `{path}`"));
        }
    }
    Ok(out)
}

fn render_file(file: &JavaFile, header: &str, support_package: &str) -> String {
    let plan = passes::resolve_imports(file);
    let r = Renderer {
        plan: &plan,
        package: &file.package,
    };
    let mut sb = String::new();
    sb.push_str(header);
    sb.push('\n');
    sb.push('\n');
    if file.is_package_info() {
        let doc = file.package_doc.clone().unwrap_or_default();
        if doc.is_empty() {
            sb.push_str("/** WIT-generated package. */\n");
        } else if doc.len() == 1 {
            sb.push_str(&format!("/** {} */\n", doc[0]));
        } else {
            sb.push_str("/**\n");
            for l in &doc {
                sb.push_str(&format!(" * {}\n", l));
            }
            sb.push_str(" */\n");
        }
        // package-info outside the support package qualifies the annotation
        // (imports cannot precede the package declaration in package-info)
        if file.package == support_package {
            sb.push_str("@WitGenerated(mapping = \"v1\")\n");
        } else {
            sb.push_str(&format!(
                "@{support_package}.WitGenerated(mapping = \"v1\")\n"
            ));
        }
        sb.push_str(&format!("package {};\n", file.package));
        return sb;
    }
    sb.push_str(&format!("package {};\n", file.package));
    sb.push('\n');
    for imp in &plan.imports {
        sb.push_str(&format!("import {imp};\n"));
    }
    if !plan.imports.is_empty() {
        sb.push('\n');
    }
    let decls = &file.decls;
    for (i, decl) in decls.iter().enumerate() {
        if i > 0 {
            sb.push('\n');
        }
        r.render_decl(&mut sb, decl, 0);
    }
    sb
}

struct Renderer<'a> {
    plan: &'a passes::ImportPlan,
    package: &'a str,
}

impl<'a> Renderer<'a> {
    fn ty(&self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Simple(s) => (*s).to_string(),
            TypeRef::Array(inner) => format!("{}[]", self.ty(inner)),
            // the annotation FQN goes through the import plan like any other
            // reference, so `@Nullable` resolves even when qualified
            TypeRef::Nullable { annotation, inner } => {
                format!("@{} {}", self.fqn(annotation), self.ty(inner))
            }
            TypeRef::Generic { fqn, args } => {
                let base = self.fqn(fqn);
                let rendered: Vec<String> = args.iter().map(|a| self.ty(a)).collect();
                format!("{base}<{}>", rendered.join(", "))
            }
            TypeRef::Fqn(fqn) => self.fqn(fqn),
        }
    }

    fn fqn(&self, fqn: &Fqn) -> String {
        if fqn.package.is_empty() || fqn.package == "java.lang" || fqn.package == self.package {
            return fqn.name.clone();
        }
        if self.plan.must_qualify.contains(&fqn.to_string()) {
            return fqn.to_string();
        }
        if self
            .plan
            .imports
            .contains(&format!("{}.{}", fqn.package, fqn.outer_simple()))
        {
            fqn.name.clone()
        } else {
            fqn.to_string()
        }
    }

    fn render_decl(&self, sb: &mut String, decl: &Decl, indent: usize) {
        let pad = "    ".repeat(indent);
        match decl {
            Decl::Record {
                name,
                javadoc,
                components,
                consts,
                methods,
                implements,
            } => {
                self.render_javadoc(sb, javadoc, indent);
                sb.push_str(&pad);
                let comps: Vec<String> = components
                    .iter()
                    .map(|c| format!("{} {}", self.ty(&c.ty), c.name))
                    .collect();
                let impls = if implements.is_empty() {
                    String::new()
                } else {
                    let list: Vec<String> = implements.iter().map(|t| self.ty(t)).collect();
                    format!(" implements {}", list.join(", "))
                };
                sb.push_str(&format!(
                    "public record {name}({}){impls} {{\n",
                    comps.join(", ")
                ));
                for c in consts {
                    sb.push('\n');
                    if let Some(doc) = &c.doc {
                        self.render_javadoc(sb, std::slice::from_ref(doc), indent + 1);
                    }
                    sb.push_str(&format!(
                        "{}    public static final {} {} = {};\n",
                        pad,
                        self.ty(&c.ty),
                        c.name,
                        c.value
                    ));
                }
                for m in methods {
                    sb.push('\n');
                    self.render_method(sb, m, indent + 1, true);
                }
                sb.push_str(&pad);
                sb.push_str("}\n");
            }
            Decl::Enum {
                name,
                javadoc,
                constants,
            } => {
                self.render_javadoc(sb, javadoc, indent);
                sb.push_str(&pad);
                sb.push_str(&format!("public enum {name} {{\n"));
                for (i, (cname, doc)) in constants.iter().enumerate() {
                    if i > 0 {
                        sb.push('\n');
                    }
                    if let Some(d) = doc {
                        self.render_javadoc(sb, std::slice::from_ref(d), indent + 1);
                    }
                    sb.push_str(&format!("{}    {},\n", pad, cname));
                }
                sb.push_str(&pad);
                sb.push_str("}\n");
            }
            Decl::Interface {
                name,
                javadoc,
                extends,
                is_sealed,
                permits,
                methods,
                nested,
            } => {
                self.render_javadoc(sb, javadoc, indent);
                sb.push_str(&pad);
                let sealed = if *is_sealed { "sealed " } else { "" };
                sb.push_str(&format!("public {sealed}interface {name}"));
                if !extends.is_empty() {
                    let exts: Vec<String> = extends.iter().map(|t| self.ty(t)).collect();
                    sb.push_str(&format!(" extends {}", exts.join(", ")));
                }
                if !permits.is_empty() {
                    // permits entries are same-file nested names: render as-is
                    sb.push_str(&format!(" permits {}", permits.join(", ")));
                }
                sb.push_str(" {\n");
                for m in methods {
                    sb.push('\n');
                    self.render_method(sb, m, indent + 1, false);
                }
                for n in nested {
                    sb.push('\n');
                    self.render_decl(sb, n, indent + 1);
                }
                sb.push_str(&pad);
                sb.push_str("}\n");
            }
        }
    }

    fn render_method(&self, sb: &mut String, m: &Method, indent: usize, in_class: bool) {
        let pad = "    ".repeat(indent);
        self.render_javadoc(sb, &m.javadoc, indent);
        for ann in &m.annotations {
            sb.push_str(&format!("{pad}{}\n", ann));
        }
        let static_kw = if m.is_static { "static " } else { "" };
        let params: Vec<String> = m
            .params
            .iter()
            .map(|p: &Param| format!("{} {}", self.ty(&p.ty), p.name))
            .collect();
        let ret = self.ty(&m.ret);
        match &m.body {
            Some(body) => {
                sb.push_str(&format!(
                    "{pad}public {static_kw}{ret} {}({}) {{\n",
                    m.name,
                    params.join(", ")
                ));
                sb.push_str(&format!("{pad}    {body}\n"));
                sb.push_str(&format!("{pad}}}\n"));
            }
            None => {
                // records need explicit `public`; interface methods are
                // implicitly public and generated bare
                let vis = if in_class { "public " } else { "" };
                sb.push_str(&format!(
                    "{pad}{vis}{static_kw}{ret} {}({});\n",
                    m.name,
                    params.join(", ")
                ));
            }
        }
    }

    fn render_javadoc(&self, sb: &mut String, lines: &[String], indent: usize) {
        if lines.is_empty() {
            return;
        }
        let pad = "    ".repeat(indent);
        if lines.len() == 1 && !lines[0].starts_with('@') {
            sb.push_str(&format!("{pad}/** {} */\n", lines[0]));
            return;
        }
        sb.push_str(&format!("{pad}/**\n"));
        let mut in_tags = false;
        let mut any_description = false;
        for l in lines {
            if l.starts_with('@') {
                if !in_tags {
                    in_tags = true;
                    // blank separator between description and tags, but not
                    // when the comment carries no description at all
                    if any_description {
                        sb.push_str(&format!("{pad} *\n"));
                    }
                }
            } else {
                any_description = true;
            }
            sb.push_str(&format!("{pad} * {}\n", l));
        }
        sb.push_str(&format!("{pad} */\n"));
    }
}
