// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.opt.v0_1.types;

/**
 * WIT-generated record.
 *
 * @param name name
 * @param retries retries
 */
public record Config(@Nullable String name, @Nullable Long retries) {
}
